import type { Activity, Board, PullRequest, Task, User } from "./types";

export const users: User[] = [
  {
    id: "u1",
    name: "Maya Chen",
    initials: "MC",
    email: "maya@acme.dev",
    role: "Admin",
    status: "Active",
    color: "#335cff",
  },
  {
    id: "u2",
    name: "Alex Rivera",
    initials: "AR",
    email: "alex@acme.dev",
    role: "Member",
    status: "Active",
    color: "#e07a5f",
  },
  {
    id: "u3",
    name: "Jordan Lee",
    initials: "JL",
    email: "jordan@acme.dev",
    role: "Member",
    status: "Active",
    color: "#4f8f72",
  },
  {
    id: "u4",
    name: "Sam Taylor",
    initials: "ST",
    email: "sam@acme.dev",
    role: "Viewer",
    status: "Active",
    color: "#9a78b8",
  },
];
const maya = users[0];
export const tasks: Task[] = [
  {
    id: "t1",
    key: "ACM-142",
    title: "Design the new onboarding flow",
    description:
      "Create a clear, welcoming onboarding experience for new workspace members.",
    status: "In Progress",
    priority: "High",
    assignee: maya,
    labels: ["Design", "Onboarding"],
    due: "Today",
    points: 5,
  },
  {
    id: "t2",
    key: "ACM-139",
    title: "Set up repository webhooks",
    description:
      "Connect GitHub events to keep tasks and pull requests in sync.",
    status: "Todo",
    priority: "Medium",
    assignee: users[1],
    labels: ["Engineering", "GitHub"],
    due: "Tomorrow",
    points: 3,
  },
  {
    id: "t3",
    key: "ACM-136",
    title: "Update empty states",
    description: "Add helpful guidance to empty board and activity views.",
    status: "In Review",
    priority: "Low",
    assignee: users[2],
    labels: ["Product"],
    points: 2,
  },
  {
    id: "t4",
    key: "ACM-131",
    title: "Improve dashboard performance",
    description: "Reduce layout shift and optimize the activity query.",
    status: "Done",
    priority: "Medium",
    assignee: maya,
    labels: ["Engineering"],
    points: 5,
  },
  {
    id: "t5",
    key: "ACM-128",
    title: "Audit keyboard navigation",
    description:
      "Make every important workspace action accessible by keyboard.",
    status: "Todo",
    priority: "Urgent",
    assignee: users[3],
    labels: ["Accessibility"],
    due: "Sep 12",
    points: 3,
  },
  {
    id: "t6",
    key: "ACM-125",
    title: "Write API integration notes",
    description: "Document the boundary between the workspace UI and API.",
    status: "Done",
    priority: "Low",
    assignee: users[1],
    labels: ["Docs"],
    points: 1,
  },
];
export const boards: Board[] = [
  {
    id: "b1",
    name: "Product roadmap",
    description: "Plan and ship the next great thing.",
    tasks,
  },
];
export const activities: Activity[] = [
  {
    id: "a1",
    actor: users[1],
    action: "moved",
    target: "ACM-139 to Todo",
    time: "12 minutes ago",
    type: "task",
  },
  {
    id: "a2",
    actor: maya,
    action: "opened pull request",
    target: "#84 Add workspace navigation",
    time: "45 minutes ago",
    type: "github",
  },
  {
    id: "a3",
    actor: users[2],
    action: "completed",
    target: "ACM-136 Update empty states",
    time: "2 hours ago",
    type: "task",
  },
  {
    id: "a4",
    actor: maya,
    action: "invited",
    target: "Taylor Kim to the workspace",
    time: "Yesterday",
    type: "member",
  },
];
export const pullRequests: PullRequest[] = [
  {
    id: "p1",
    title: "Add workspace navigation",
    number: 84,
    author: maya,
    status: "Open",
    repo: "acme/web",
    taskKey: "ACM-142",
    updated: "45 minutes ago",
  },
  {
    id: "p2",
    title: "Refine task card interactions",
    number: 82,
    author: users[1],
    status: "Open",
    repo: "acme/web",
    taskKey: "ACM-139",
    updated: "Yesterday",
  },
  {
    id: "p3",
    title: "Update dashboard queries",
    number: 79,
    author: users[2],
    status: "Merged",
    repo: "acme/api",
    taskKey: "ACM-131",
    updated: "Sep 5",
  },
];
export const workspaces = [
  "Acme Engineering",
  "Acme Design",
  "Personal workspace",
];
